### ISSUE TITLE
Events are being fired twice

### ISSUE THREAD

**Issue by Fire-Brand** [MailOnline/VPAIDHTML5Client#7] opened 2015-10-19 12:34 UTC
Hi, i'm experiencing an issue where every time-event is being fired twice one right after the other.
Happens on all browsers on windows
any idea why this could happen?

**Comment by lizozom** [comment] 2015-11-23 14:27
Getting the same issue.

**Comment by Fetz** [comment] 2015-11-24 01:38
Hi sorry the late delay answering, is happening in the demo page or with some specific ad?

If is with the demo page:

I checked the issue and is not happening with the dummy ad that I created
`https://github.com/MailOnline/VPAIDHTML5Client/blob/master/demo/VPAIDAdLinear.js`

but is happening with the brainient ad: 
https://github.com/MailOnline/VPAIDHTML5Client/blob/master/demo/index.html#L23

so if you comment this code like this:
```javascript
var urls = [
/*
                {
                    url: 'http://cdn-assets.brainient.com/2015/mailonline_example/vpaid.js',
                    adParameters: ''
                },
*/
                {
                    url: 'VPAIDAdLinear.js',
                    adParameters: JSON.stringify(
```

You should see the events only firing once.


Either way I debugged and I confirmed that there is a bug with that ad from brainient, I will try to find another ad to use...

If you want to debug yourself (because code don't lie):
=========================================

in https://github.com/MailOnline/VPAIDHTML5Client/blob/master/js/VPAIDAdUnit.js#L190
log the number of times an event that should fire once per ad is subscribed for example: ` AdVideoStart`.

https://github.com/MailOnline/VPAIDHTML5Client/blob/master/js/VPAIDAdUnit.js#L214
log the number of the times this function with that event is called, is should be the same number of subscriptions.

I they are different then there is a bug with the ad creative, if they are the same but you are still seeing the event being fire twice then there is a bug with the VPAIDHTML5Client

**Comment by lizozom** [comment] 2015-12-22 12:18
I managed to reproduce the issue the following way, with static VAST data and a static creative:

1. Create an ad unit (adUnit1) and load a link to a creative that returns the error. Initialization is just as described in your documentation.
2. Destroy the ad unit (I was hoping this would solve the issue, but it didn't).
3. Create another ad unit (adUnit2) and load a link to a creative that works. adUnit2 will trigger all its events twice!

I think there's a problem with the unsubscribe method (looking into it, maybe you have some insights?).

Liz

**Comment by Fetz** [comment] 2016-01-15 11:40
@Fire-Brand I'm closing this issue since everything looks ok. Anything feel free to reopen if you find something

**Closed by Fetz** 2016-01-15 11:40 UTC
